This word search allows words to be horizontal, vertical, diagonal,
written backwards, or even overlapping other words. It's a little
unusual, though, as you don't merely need to find one instance of
XMAS - you need to find all of them.

Take a look at the little Elf's word search. How many times does XMAS
appear?

** Idea

So the search will have to go 8 directions:
- left to right
- right to left
- top to bottom
- bottom to top
- diagonal NE to SW
- diagonal SW to NE
- diagonal NW to SE
- diagonal SE to NW

And of course, every row, column and diagonal in each direction. Phew!

String search from left to right should be relatively easy, just use
normal string searching on each line.

If you search within the buffer, rather than the buffer string, you
can use search-forward and search-backward. Regular expression
searching can search strings. So we can slice and dice the buffer
string a few ways, use reverse to get strings to search backwards. It
will probably be easier to do all directions this way:

- Cut up (buffer-string) the appropriate way into a list of
  strings. Horizontal lines are the easiest.
- Search the strings forwards.
- Search the (reverse string), i.e. search backwards.

Of course, keep a total count.

One idea for horizontal is to how how-many to count occurrences of
XMAS and SAMX. One could do the SAMX trick for all directions, and
forget about using reverse!

For vertical and diagonal searches, I don't know if it will be more
efficient to build a list of strings for each, and use regexp search
on those strings, or just search directly by accessing the individual
characters. I /think/ it is more straightforward and reliable to just
create the strings and search them.

** Horizontal

Create line strings from buffer string using string-lines and search them
for XMAS and SAMX.

Maybe skip creating lines and just search thought the buffer string.

** Vertical

Get horizontal line length from first string in the horizontal strings
list.

For each index from 0 to length of line - 1, grab the index'th
character from each line to create a vertical line. The grid looks to
be 140 × 140, so as a check, we should have 140 verticals lines of 140
characters each.

Once created, search for XMAS and SAMX in each string.

** Diagonals

We should get 279 lines each from the NE-SW and NW-SE diagonals. A few
of the lines will be too short to hold XMAS or SAMX.

Then search for XMAS and SAMX in each string.
